### ISSUE TITLE
Byte stream interfaces - the fine print.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpcore#1]
We've got a byte stream interface on both the request and response bodies. There's a few bits there that'll need a bit of careful description:

* We'll want both of those to also expose `.close()` methods.
* We're not going to provide any smart context managment to automatically call `.close()`, but clients should almost always do so. (eg. `httpx`'s context-managed stream API)
* If we want to support trailing headers, then we probably want the `close()` method to return a list of headers (which will typically be an empty list).
* We probably want folks to be able to implement against the proposed interface here even without depending on `httpcore`, but simply by matching its type signatures. We can't do that if we introduce a class that streams my strictly subclass. We *might?* want to annotate the stream types as `AsyncIterable[bytes]` and `Iterable[bytes]` with the close method being an optional under-typed method. (Ie. client code can use `close = getattr(stream, 'close')`)

**Comment by florimondmanca** [comment]
Alternatively, we can use`AsyncGenerator` / `Generator`. Those types expose a `.aclose()`(!) / `.close()` method. But ideally I think what we’d want here is trio’s `ClosableResource` interface (or is it just `Resource`?).

**Comment by tomchristie** [comment]
Eh, I’m over-complicating this right. We should just expose SyncByteStream and AsyncByteStream interfaces.

**Comment by florimondmanca** [comment]
> We should just expose SyncByteStream and AsyncByteStream interfaces.

Not sure I follow — would those be `Iterator[bytes]`/`AsyncIterable[bytes]`?

**Comment by tomchristie** [comment]
Classes with __iter__/__aiter__ and close methods

**Comment by florimondmanca** [comment]
I see, so…

```python
import typing

class AsyncByteStream(typing.Protocol):
    async def __aiter__(self) -> typing.AsyncIterator[bytes]: ...
    async def close(self) -> None: ...  # Or aclose()?

class SyncByteStream(typing.Protocol):
    def __iter__(self) -> typing.Iterator[bytes]: ...
    def close(self) -> None: ...
```

(Doesn't have to be a `Protocol` but at least that allows us to use pure duck-typing, without requiring stuff passed as streaming data to be "a subclass of XYZ" or "strictly a generator".)

**Comment by tomchristie** [comment]
Yup, that's about it. I've added AsyncByteStream and SyncByteStream interfaces now.

Right now we've got `async def close` -> `def close`. We *could* change that although I'm not sure either way. At *this* interface level it feels like anything that's not a magic method should keep the same unasync'ed name, but open to going the other way on it too.

**Comment by florimondmanca** [comment]
> At this interface level it feels like anything that's not a magic method should keep the same unasync'ed name

Well, my line of thinking was that `.aclose()` sort of *is* a special method name, as it's what is exposed by async generator-like objects:

```python
async deg agen():
    yield b''

g = agen()
g.asend
g.athrow
g.aclose
```

It's a rather sensible convention IMO, e.g. Trio decided to follow that convention for its `AsyncResources`, e.g. `SocketStream`: `await stream.aclose()` ...

**Comment by tomchristie** [comment]
> Well, my line of thinking was that .aclose() sort of is an async-special method name, as it's what is exposed by async generator-like objects:

Fair, yup.
