### ISSUE TITLE
connection leak in async connection pool

### ISSUE THREAD

**Issue by hzliu** [encode/httpcore#116]
in AsyncConnectionPool.request

```python
            except Exception:
                logger.trace("remove from pool connection=%r", connection)
                await self._remove_from_pool(connection)
                raise
```

the connection is not closed.

**Comment by tomchristie** [comment]
Closing this off as stale

**Comment by elupus** [comment]
I would say not stale. I just had the exact same issue. If you get a RemoteProtocolError(msg) of "Server disconnected without sending a response. ", the socket in the connection pool will be removed from the pool, but will not be closed. Maybe it eventually get garbage collected, but that takes quite some time. During which the server on the other side can't close the socket down completely.

**Comment by elupus** [comment]
This is like the main culprit behind a long running issue against philips tv's ( which i've blamed on buggy TVs :) )
https://github.com/home-assistant/core/issues/57093
https://github.com/home-assistant/core/issues/49801#issuecomment-931645725
