### ISSUE TITLE
Switch tests to using local server.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpcore#12]
Currently the test suite makes live requests to `http://example.org`.

We need to update those to run against uvicorn or hypercorn instead.

The advantage of uvicorn would be that we can keep it in supported-versions lockstep with `httpcore`.
The advatage of hypercorn would be that we can run any HTTP/2 tests.

Figure we probably(?) ought to stick with uvicorn as with httpx for right now, since that ought to get us up and going as quickly as possible, but might not be averse to switching to hypercorn if it makes sense sometime.

**Comment by victoraugustolls** [comment]
Quick question:

Wouldn't it make sense to use `uvicorn` and maybe put effort [here] (https://github.com/encode/uvicorn/issues/47), having no need for `hypercorn`?

**Comment by tomchristie** [comment]
Potentially yes.

**Comment by tomchristie** [comment]
Going to close this issue off, since *actually* I think it's probably quite a good thing that we have integration tests against a live server that's not running a Python implementation. We'd obviously still *also* like to expand the tests out, but I don't think we should be switching out the existing `example.com` tests, they're actually pretty sensible.

**Comment by risicle** [comment]
This means we're going to have to disable most of the tests for the build process of the Nix packages. Not only because our build process is sandboxed, but because interacting with external servers makes the results non-reproducible.
