### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by martinka** [encode/httpcore#122]
I am using an HTTPS proxy, with the httpx 0.13.3 and httpcore 0.9.1 client on Mac OS (Darwin 19.5.0) httpx is the only direct dependency I have loaded... abbreviated stack trace
...
httpcore/_sync/httpx_proxy.py line 111 in request
httpcore/_sync/httpx_proxy.py line 214 in _tunnel_request
httpcore/_sync/connection.py line 126 in start_tls
httpcore/_sync/http11.py line 71 in start_tls
httpcore/_backends/sync.py line 50 in start_tls
    self.sock, server_hostname=hostname.decode("ascii")
version/3.7.4/lib/python3.7/contextlib.py, line 130, in __exit__

httpcore._exceptions.ConnectError: [SSL: PRE_MAC_LENGTH_TOO_LONG] invalid alert (_ssl.c:1076)

I have tried increasing debug to trace level without anything more illuminating.   the proxy works correctly with curl.  I am not sure this is an actual bug but not sure how to proceed. 

Here is the verbose TLS output from curl that worked:
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Change cipher spec (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-AES128-GCM-SHA256
* ALPN, server did not agree to a protocol

 Not sure if the last line there is a clue but it seems odd.   Any help greatly appreciated.

**Comment by florimondmanca** [comment]
Hi!

Does the request succeed when using another Python-based HTTP client, such as `requests`?

**Comment by martinka** [comment]
Funny you should ask.. I just tried requests and it is getting a different error but also errors out.  I have reached out to the proxy providers to see if there is something going on there, since the requests code is their example code more or less.  Requests is showing.. http.client.RemoteDisconnected: Remote end closed connection without response.

**Comment by florimondmanca** [comment]
Okay.

I'd suggest figuring out what could be wrong with your proxy provider then, doesn't seem clear to me that there's an issue particularly with HTTPCore…

I'll close for now but if you end up in a state where Requests works while HTTPX doesn't, feel free to reach back. :-)
