### ISSUE TITLE
Question about get_http_version() in SocketStream

### ISSUE THREAD

**Issue by ganeshmurthy** [encode/httpcore#123]
I was looking at the get_http_version() function in SocketStream:
```python
class SocketStream(AsyncSocketStream):
    def __init__(
        self, stream_reader: asyncio.StreamReader, stream_writer: asyncio.StreamWriter,
    ):
        self.stream_reader = stream_reader
        self.stream_writer = stream_writer
        self.read_lock = asyncio.Lock()
        self.write_lock = asyncio.Lock()

    def get_http_version(self) -> str:
        ssl_object = self.stream_writer.get_extra_info("ssl_object")

        if ssl_object is None:
            return "HTTP/1.1"
```
So, it looks like if there is no SSL setup, the http version will always be HTTP/1.1
So, even if I specify http2=True with no SSL, the connection is always a HTTP/1.1 connection
Is there a way to do HTTP/2 over a connection with no SSL ?

Thanks.

**Comment by florimondmanca** [comment]
Hello!

Currently we only support HTTP/2 with HTTPS, which is why no SSL -> HTTP/1.1.

There is related discussion about supporting unencrypted HTTP/2 (by adding support for `h2c` upgrades) here: https://github.com/encode/httpx/issues/503
