### ISSUE TITLE
Increasing read chunk size could improve performance for large responses

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpcore#135]
Coming from discussion on Gitter with @dalf…

Currently we are reading response data in chunks of 4kB…

https://github.com/encode/httpcore/blob/f4240b64735ce5cafcfed24b6417c16d61a034df/httpcore/_async/http11.py#L26

https://github.com/encode/httpcore/blob/f4240b64735ce5cafcfed24b6417c16d61a034df/httpcore/_async/http2.py#L29

Benchmarking using @dalf's [pyhttp-benchmark](https://github.com/dalf/pyhttp-benchmark) tool [led us to see](https://gitter.im/encode/community?at=5f29128161a831684637a1b1) that increasing this number to 64kB could lead 2-3x execution time improvement for large responses (typically > 256kB).

My rationale would be that reading N bytes in one go via a syscall is faster than reading n = N/k bytes k times — mostly because the kernel is way faster than Python.

**Comment by florimondmanca** [comment]
Running the 1MB-response benchmark for various `READ_NUM_BYTES` values, and a matplotlib script later, here's a handy little plot to support this assessment that 64kB is probably a good value…

```python
import matplotlib.pyplot as plt

data = [
    (4, 2.36, 2.13),
    (16, 1.18, 0.99),
    (32, 1.07, 0.94),
    (64, 0.95, 0.81),
    (96, 0.87, 0.74),
    (128, 0.82, 0.68),
    (160, 0.80, 0.66),
]

x, runtime, cpu = zip(*data)

plt.grid()
plt.xlabel("READ_NUM_BYTES (kB)")
plt.xticks(range(0, 192, 16))
plt.ylabel("Median execution time (s)")
plt.scatter(x, runtime)
plt.scatter(x, cpu)
plt.legend(["runtime", "cpu"])
plt.show()
```

![plot](https://user-images.githubusercontent.com/15911462/89440903-a097a300-d74c-11ea-89de-aeaccd3fd0f1.png)

Looks like the median execution time gets exponentially smaller as we increase the chunk size. Once we hit 32kB we see we're not getting as much from increasing it more. 64kB gets us "below 1s for a 1MB response" and that sounds very satisfying. :-)

**Comment by dalf** [comment]
An additional graph (made using [this tool](https://github.com/dalf/pyhttp-benchmark/blob/master/csv2graph.py)):  
![image](https://user-images.githubusercontent.com/1594191/89453056-f117fc00-d75e-11ea-997a-77c4099aebee.png)
* ```httpcore_True_*```:  http2=True
* ```httpcore_False_*``` : http2=False
