### ISSUE TITLE
AsyncConnectionPool leaks connection on CancelledError on 3.8

### ISSUE THREAD

**Issue by lazitski-aliaksei** [encode/httpcore#149]
From python 3.8 `CancelledError` a is subclass of `BaseException` (https://docs.python.org/3.8/library/asyncio-exceptions.html#asyncio.CancelledError)

If coroutine is cancelled after connection was acquired and during request, connection is not removed from the pool:
https://github.com/encode/httpcore/blob/master/httpcore/_async/connection_pool.py#L179
```
try:
    response = await connection.request(
        method, url, headers=headers, stream=stream, timeout=timeout
    )
except NewConnectionRequired:
    connection = None
except Exception:
    logger.trace("remove from pool connection=%r", connection)
    await self._remove_from_pool(connection)
    raise
```

**Comment by tomchristie** [comment]
Related #116
