### ISSUE TITLE
Add tests for ConnectionPool

### ISSUE THREAD

**Issue by jcugat** [encode/httpcore#155]
In https://github.com/encode/httpcore/pull/153 was noticed that the parameters `max_keepalive_connections` / `max_connections` were not handled correctly in `AsyncConnectionPool` and `SyncConnectionPool`. Add some tests to cover it.

**Comment by cdeler** [comment]
@jcugat I added the tests, but they are failing without the changes from https://github.com/encode/httpcore/pull/153 (I mean without `self._max_keepalive = max_keepalive` -> `self._max_keepalive = max_keepalive_connections`)
