### ISSUE TITLE
Provide a `get_connection_stats()` interface.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpcore#18]
We should hide anything except `.request` and `.close` on the ConnectionPool, but we *might well* want to provide a `.get_connection_stats()` that returns eg...

```python
>>> print(http.get_connection_stats())
{(b'https', b'example.org', 443): {ConnectionState.IDLE: 1}}
```

*Above: A connection pool, maintaining a single keep-alive connection to https://example.org*

Noticable in particular in the test cases which happen to reach inside intended-private API in order to deteremine the connection state.

**Comment by victoraugustolls** [comment]
would this include making the properties private?

eg. `max_connections` -> `_max_connections`, `connection_semaphore` -> `_connection_semaphore`, ...

**Comment by tomchristie** [comment]
At this point in time really all the interface on `AsyncConnectionPool` / `SyncConnectionPool` *ought* to be made private, other than `request()` and `.close()`/`.aclose()`.
