### ISSUE TITLE
Using `select` is causing issues when many files are open

### ISSUE THREAD

**Issue by gsmcwhirter** [encode/httpcore#182]
In the internals of the httpcore sync client, there is a call to select.select that fails when there is not a fd available < 1024. This can occur when there are already many open files prior to using httpx (and thereby httpcore).  A similar problem occurred in urllib3 a while ago (see references below).

References: 
- https://github.com/boto/botocore/issues/756
- https://github.com/urllib3/urllib3/issues/589

Python Verson: 3.6.8

Traceback:
```
...
File "/var/starterview/common/py/http_client/httpx.py", line 1440, in post
    json=json)
  File "/var/starterview/common/py/http_client/httpx.py", line 379, in do_sync
    resp = func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/httpx/_client.py", line 932, in post
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/httpx/_client.py", line 674, in request
    request, auth=auth, allow_redirects=allow_redirects, timeout=timeout
  File "/var/starterview/common/py/http_client/httpx.py", line 640, in wrapper
    resp = func(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/httpx/_client.py", line 704, in send
    request, auth=auth, timeout=timeout, allow_redirects=allow_redirects
  File "/usr/local/lib/python3.6/dist-packages/httpx/_client.py", line 733, in _send_handling_redirects
    request, auth=auth, timeout=timeout, history=history
  File "/usr/local/lib/python3.6/dist-packages/httpx/_client.py", line 769, in _send_handling_auth
    response = self._send_single_request(request, timeout)
  File "/usr/local/lib/python3.6/dist-packages/httpx/_client.py", line 803, in _send_single_request
    timeout=timeout.as_dict(),
  File "/usr/local/lib/python3.6/dist-packages/httpcore/_sync/connection_pool.py", line 172, in request
    connection = self._get_connection_from_pool(origin)
  File "/usr/local/lib/python3.6/dist-packages/httpcore/_sync/connection_pool.py", line 217, in _get_connection_from_pool
    if connection.is_connection_dropped():
  File "/usr/local/lib/python3.6/dist-packages/httpcore/_sync/connection.py", line 148, in is_connection_dropped
    return self.connection is not None and self.connection.is_connection_dropped()
  File "/usr/local/lib/python3.6/dist-packages/httpcore/_sync/http11.py", line 193, in is_connection_dropped
    return self.socket.is_connection_dropped()
  File "/usr/local/lib/python3.6/dist-packages/httpcore/_backends/sync.py", line 81, in is_connection_dropped
    rready, _wready, _xready = select.select([self.sock], [], [], 0)
ValueError: filedescriptor out of range in select()```

**Comment by gsmcwhirter** [comment]
Snippet to reproduce (needs to be run on a system where python is allowed to have enough files open to exhaust the low fds):

```
import httpx

fhs = []
while True:
    fh = open("/dev/null")
    if fh.fileno() > 1024:
        fh.close()
        break
    fhs.append(fh)

try:
    client = httpx.Client()
    while True:
        client.head("https://www.google.com")
finally:
    for fh in fhs:
        fh.close()
```

**Comment by florimondmanca** [comment]
Woah, and the related issue in urllib3 resulted in them adding custom selectors with a hugely sized PR here… https://github.com/urllib3/urllib3/pull/1001

Since we plan to use more of the `select()` trick to detect dropped connections (eg in #169), this is definitely worth looking into some more…

I tried to reproduce on my side (on macOS) using this slimmed down snippet that only uses `httpcore`, and prints the request number as it progresses…

```python
from itertools import count
import httpcore

fhs = []
while True:
    fh = open("/dev/null")
    if fh.fileno() > 1024:
        fh.close()
        break
    fhs.append(fh)

try:
    with httpcore.SyncConnectionPool() as transport:
        method = b"HEAD"
        url = (b"https", b"www.google.com", None, b"/")
        headers = [(b"host", b"www.google.com")]
        for n in count(0):
            print(f"Request {n}")
            *_, stream = transport.request(method, url, headers)
            stream.close()
finally:
    for fh in fhs:
        fh.close()
```

Interestingly, I was not able to reproduce, as the script goes on well beyond `Request 1024`, eg I was able to go through `Request 1836` and exited (but it could have continued).

To be honest I'm not sure I fully grok the OS-level mechanisms at play here, eg whether this would be a Linux-only issue,

**Comment by florimondmanca** [comment]
@gsmcwhirter I pushed #185 to try and tackle this with a stdlib solution (urllib3 had to backport, but that code is available in the stdlib `selectors` module for us on 3.6+).

Could you try and install httpcore from that branch, and then see if this solves the behavior you're seeing?

Installing from the branch should be doable using something like this:

```bash
pip install git+https://github.com/encode/httpcore.git@fm/selectors#egg=httpcore
```

Thanks! :pray:

**Comment by cdeler** [comment]
A small addition to the ticket

According to Linux [man 2 select](https://man7.org/linux/man-pages/man2/select.2.html):
>     To monitor file descriptors greater than 1023, use poll(2) or epoll(7) instead

So it what has proposed int the PR https://github.com/encode/httpcore/pull/185/files

According to BSD (OS X too) [man 2 select](https://www.freebsd.org/cgi/man.cgi?select):
> The default size of FD_SETSIZE is currently 1024.

So that using `epoll` or `kqueue` is only the way to handle that

**Comment by agronholm** [comment]
And what would you do on Windows then?

**Comment by agronholm** [comment]
Can we just do `sock.recv(1, socket.MSG_PEEK)`? This should work on Windows too.

**Comment by agronholm** [comment]
OTOH, if there *is* data in the buffer, it can't tell us whether the connection has been dropped or not.

**Comment by cdeler** [comment]
Unfortunately Windows `FD_SETSIZE` is `512` :-( 

https://github.com/python/cpython/blob/d051801052211b533c46a593b1c1bccf649a171c/Modules/selectmodule.c#L29-L37
