### ISSUE TITLE
We should use the unasync package (and unasync should check for stale files in output dir)

### ISSUE THREAD

**Issue by johtso** [encode/httpcore#214]
`unasync.py --check` will currently happily allow stale files in `_sync`. It would be simple enough to make the tool treat the destination directory as fully managed and make sure it strictly matches the output of unasyncing `_async` with no extra files.

At the same time it would probably be good to improve / start using the `unasync` package so that effort isn't getting repeated.

See:
https://github.com/python-trio/unasync/issues/66
https://github.com/python-trio/unasync/issues/68
https://github.com/python-trio/unasync/issues/69

**Comment by pquentin** [comment]
We would be happy to collaborate here! @johtso If you get one pull request merged in the python-trio org, you'll be invited as a collaborator to approve pull requests, and we'd be happy to allow you making releases too.

**Comment by johtso** [comment]
@pquentin hope to have a bit of time to do more than just open issues soon :)
