### ISSUE TITLE
Inefficient concatenation in the readme

### ISSUE THREAD

**Issue by mixmastamyk** [encode/httpcore#24]
body = b''
        async for chunk in stream:
            body += chunk

This gets slower and slower as the size of body grows.  Best to use a list and .join() at the end.

**Comment by florimondmanca** [comment]
Or maybe `body = b''.join(chunk async for chunk in stream)` (a generator expression, skips the list part)? :)

**Comment by mixmastamyk** [comment]
Well, join will create a list if you don't, so it is practically the same.  A list comp may be faster:

https://stackoverflow.com/q/34822676/450917

**Comment by florimondmanca** [comment]
Interesting, yeah. Though I’m afraid we might be experiencing a prime situation of yak shaving here. 😄

**Comment by tomchristie** [comment]
Now resolved in master, thanks folks!

**Comment by mixmastamyk** [comment]
Yes, though it is more important that it might first seem.  If you are hoping to promote a new library heavily dependent on performance, then having a common CS blunder in the first ten lines of the readme is not a good look.  It happens of course, just trying to help.  Cheers.

**Comment by tomchristie** [comment]
As it happens it was an *intentional* choice to just opt for a plain vanilla style example.

But yeah, probably better to use the `b””.join(...)` style, so.
