### ISSUE TITLE
Missing comma in example code

### ISSUE THREAD

**Issue by aitorcalero** [encode/httpcore#336]
There is a missing comma in the example provided:

`with httpcore.SyncConnectionPool() as http:

    status_code, headers, stream, extensions = http.handle_request(

        method=b'GET',

        url=(b'https', b'example.org', 443, b'/'),
        headers=[(b'host', b'example.org'), (b'user-agent', b'httpcore')] **here**
        stream=httpcore.ByteStream(b''),
        extensions={}
    )
    body = stream.read()
    print(status_code, body)`

**Comment by johtso** [comment]
Thanks @aitorcalero!
