### ISSUE TITLE
Coroutine never awaited

### ISSUE THREAD

**Issue by victoraugustolls** [encode/httpcore#34]
On [http_proxy.py](https://github.com/encode/httpcore/blob/8f1f226a0d07a1be04145cdbc673b453e0da0a29/httpcore/_async/http_proxy.py#L153) coroutine is never awaited and return is never used. Is this on purpose?

Line:
`read_body(proxy_stream)`

**Comment by tomchristie** [comment]
Not intentional, thanks. We're missing any coverage there at the moment.
