### ISSUE TITLE
Performance issue on 0.13.4

### ISSUE THREAD

**Issue by jhagege** [encode/httpcore#359]
Hi, we have noticed performance regression on 0.13.4, when comparing with 0.13.3.
When performance testing our workload, we get 9QPS, vs 14QPS previously.
Not sure what exactly is causing the regression (maybe migrating to anyio), but I would recommend investigating.
Thanks for the great package :)

**Comment by tomchristie** [comment]
If anyone fancies a neat little side task, then a little basic benchmarking here might be a good idea.
