### ISSUE TITLE
UnsupportedProtocol is raised with badly formatted message

### ISSUE THREAD

**Issue by plotski** [encode/httpcore#360]
There should be a closing quote in front of the backslash and a new opening quote on the next line.

https://github.com/encode/httpcore/blob/98fb2a0814d1fd076a354804f071cdcef9812615/httpcore/_async/connection_pool.py#L203  
https://github.com/encode/httpcore/blob/98fb2a0814d1fd076a354804f071cdcef9812615/httpcore/_async/connection_pool.py#L208

**Comment by tomchristie** [comment]
Resolved in 0.14
