### ISSUE TITLE
using deprecated SSLContext() with no ssl.PROTOCOL_TLS_CLIENT flag

### ISSUE THREAD

**Issue by graingert** [encode/httpcore#384]
see https://github.com/encode/httpcore/blob/c8fdef098483e1265907fefe6279d2bd5593d2ed/httpcore/_async/connection_pool.py#L128

**Comment by graingert** [comment]
I tried setting this to `SSLContext(ssl.PROTOCOL_TLS_CLlENT)` but then ssl couldn't get the local issuer certificate of hypercorn

**Comment by tomchristie** [comment]
This is..... *brief*. 😅

What's the issue here?

**Comment by graingert** [comment]
> This is..... _brief_. 😅
> 
> What's the issue here?

Calling `SSLContext()` (with no arguments) is deprecated and throws a warning with them enabled

**Comment by tomchristie** [comment]
Ah yes... https://docs.python.org/3/library/ssl.html#ssl.SSLContext

> Deprecated since version 3.10: SSLContext without protocol argument is deprecated. The context class will either require PROTOCOL_TLS_CLIENT or PROTOCOL_TLS_SERVER protocol in the future.

Assume this is no longer valid, since we're using `ssl.create_default_context()` now... https://github.com/encode/httpcore/blob/master/httpcore/_ssl.py
