### ISSUE TITLE
Usage of __slots__

### ISSUE THREAD

**Issue by victoraugustolls** [encode/httpcore#39]
Is the usage of __slots__ something to consider? I know some of the benefits are lower memory footprint and faster attribute access and I am curious if it something to consider here.

**Comment by tomchristie** [comment]
Fair question yes.
It's likely to be negligable in a networking library like `httpcore`. Feasible that it *might* be worth considering at a point in the future, given sufficient evidence, but not something I'd want to do at the moment.

**Comment by victoraugustolls** [comment]
Thanks for the answer!
