### ISSUE TITLE
Thoughts on the "Interface" suffix

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpcore#4]
Currently we have here:

- `AsyncDispatchInterface`
- `SyncDispatchInterface`

The `Interface` suffix looks a bit jarring to me, as in "*of course* they are interfaces, aren't they?".

What was the motivation for departing from `AsyncDispatcher`/`SyncDispatcher`?

**Comment by florimondmanca** [comment]
Other potential naming, inspired by https://github.com/python-trio/hip/issues/124#issuecomment-529412759, would be that of "transports", e.g...

- `AsyncHTTPTransport`
- `SyncHTTPTransport`

**Comment by kousikmitra** [comment]
@florimondmanca What about these?

- `AsyncHTTPConnection`
- `SyncHTTPConnection`

**Comment by tomchristie** [comment]
Rolling with `AsyncHTTPTransport`/`SyncHTTPTransport` at the moment. Open to design discussions continuing on this, but that feels right for now.
