### ISSUE TITLE
Proxy tests

### ISSUE THREAD

**Issue by tomchristie** [encode/httpcore#42]
I think a sensible tack onto the proxy tests would be if our test environment included a running client proxy, and we made live requests via it.

I'm wondering what the most well used client proxy services are that we'd be able to have easily  installed into our Travis / GitHub actions / Local developer setup, that we could use to exercise forwarding/tunneling requests?

Anyone got thoughts on which services we could easily have installed into the docker environment that'd meet our requirements here?

**Comment by yeraydiazdiaz** [comment]
Closed via #48
