### ISSUE TITLE
About 4-tuple URLs

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpcore#5]
The documentation currently reads:

> **url** - (bytes, bytes, int, bytes) - The URL as a 4-tuple of (scheme, host, port, path).

Where does userinfo fit into this, e.g. `foo:bar` in `http://foo:bar@mysite.com/some/path`?

- Is it considered as part of the `host`? Should `host` actually be `authority`?
- So, should URLs actually be 5-tuples of (scheme, userinfo, host, port, path)?
- Or maybe a more complex (scheme, (username, password, host, port), path)?
- Or maybe a [`TypedDict`](https://www.python.org/dev/peps/pep-0589/)?

```python
import typing

class URL(typing.TypedDict, total=False):
    scheme: bytes
    username: bytes
    password: bytes
    host: bytes
    port: int
    path: bytes

url: URL = {
    "scheme": b"http",
    "host": b"localhost",
    "port": 8000,
    "path": b"/hello?beautiful=world#today"
}
```

**Comment by tomchristie** [comment]
userinfo doesn’t fit in at all at this layer.

Higher level clients can use that info to construct an appropriate basic auth header if it is present in the URL. The transport doesn’t get any visibility into it.

**Comment by florimondmanca** [comment]
Ah, makes sense.

Regarding the dict representation — I assume URLs have this natural "from left to right" vibe that tuples convey rather well, so we're probably better off sticking to tuples.
