### ISSUE TITLE
Enable Mypy `--strict` internally

### ISSUE THREAD

**Issue by michaeloliverx** [encode/httpcore#514]
I think being compatible with mypy `--strict` benefits end users who are also using it, if https://github.com/encode/httpcore/pull/513 is merged then there isn't much work left to be compatible with strict mode.

See also https://github.com/encode/httpcore/issues/512

**Comment by michaeloliverx** [comment]
What do @encode/maintainers think of this?

**Comment by adriangb** [comment]
Would we do it only for the codebase or also for tests? The benefit of doing it for tests is that you get to asses what the experience would be like for a user in strict mode.

**Comment by adriangb** [comment]
I see you did both in your PR. I'm in favor of it 😁

**Comment by tomchristie** [comment]
Based on #524 I'd probably be somewhat against it - looks like extra noise & fluff from my perspective.

**Comment by michaeloliverx** [comment]
> Based on #524 I'd probably be somewhat against it - looks like extra noise & fluff from my perspective.

I agree its quite a bit of noise.. another option would be to do it incrementally as files are changed?

**Comment by RA80533** [comment]
> Based on #524 I'd probably be somewhat against it - looks like extra noise & fluff from my perspective.

Are there particular changes in the PR that you would rather see addressed separately, @tomchristie?

1. Narrowing `# type: ignore` to a particular class of error
2. Correcting incomplete `dict` and `list` types
3. Using type aliases on values with domain significance (`HeadersAsMapping` versus `dict`)
4. Casting types brought in from the h2 package

2\. is the most important for the purpose of the PR. Each correction means one less error showing up to the user in VS Code.

**Comment by graingert** [comment]
adding typing in anyio found a large number of type level bugs, I'm in favor of this change - so unmarking stale

**Comment by adriangb** [comment]
I think we probably want to turn on `--strict` one file at a time right?

**Comment by tomchristie** [comment]
Yeah that sort of thing.
It'd probably be okay to make the fixes incrementally, without necessarily ratcheting them in using the CI.
We could improve them bit by bit and only hard-enforce it once we get there.

**Comment by tomchristie** [comment]
See https://github.com/encode/httpx/issues/2436 for how I think we should approach this.
