### ISSUE TITLE
Consider dropping Python 3.6 support

### ISSUE THREAD

**Issue by michaeloliverx** [encode/httpcore#515]
Python 3.6 is now considered legacy[^python-3.6-legacy], we should remove support and drop any compatibility shims in place:
https://github.com/encode/httpcore/blob/ebf06848463a76492459e59221d665511afd52e2/httpcore/_compat.py#L1-L6

[^python-3.6-legacy]:  [The release you are looking at is Python 3.6.0, the initial feature release for the legacy 3.6 series which has now reached end-of-life and is no longer supported.](https://www.python.org/downloads/release/python-360/)

**Comment by tomchristie** [comment]
Yup to this, given https://github.com/encode/httpx/pull/2097.
