### ISSUE TITLE
Add types for `extensions` using `typing.TypedDict`

### ISSUE THREAD

**Issue by michaeloliverx** [encode/httpcore#523]
I think it would increase DX if we typed `extensions` using `TypedDict`.

Example:

<img width="280" alt="image" src="https://user-images.githubusercontent.com/55017335/156227311-a2fa842b-1d39-4c67-9e90-13a9d6793051.png">

<img width="280" alt="image" src="https://user-images.githubusercontent.com/55017335/156227461-492aef6a-a223-4e22-a48c-24acf5d1ade7.png">

We would need to add the `typing-extensions` package for versions below 3.8 to use `TypedDict`.

## References
- https://www.python.org/dev/peps/pep-0589/

**Comment by florimondmanca** [comment]
I think this would be a rather nice developer experience addition at a rather low-cost. Would also be an improvement for HTTPCore, by helping prevent using wrong extension name/value types.

**Comment by vladNed** [comment]
working on this
