### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by RA80533** [encode/httpcore#542]
https://github.com/encode/httpx/pull/2096 is currently blocked pending a new release of httpcore.[^1]

[^1]: https://github.com/encode/httpx/pull/2096#issuecomment-1085628949

**Comment by vfazio** [comment]
Any chance this will be scheduled soon? It's be great to get the trio fix for #544 in the next release and have httpx use bump its dependency

**Comment by florimondmanca** [comment]
Don't really have time to hop on this, but if someone's up for helping out, we do have an automated release pipeline here which looks very much like the one on the HTTPX repo - instructions here: https://www.python-httpx.org/contributing/#releasing

**Comment by tomchristie** [comment]
Release pull request... https://github.com/encode/httpcore/pull/547

**Comment by tomchristie** [comment]
Closed via https://github.com/encode/httpcore/pull/547
