### ISSUE TITLE
migrate documentation to the new experimental python handler

### ISSUE THREAD

**Issue by graingert** [encode/httpcore#560]
bumping the mkdocs deps was needed to support jinja2==3.1.2 in https://github.com/encode/httpcore/pull/546/files however we're still using the legacy python handler and we should upgrade https://mkdocstrings.github.io/handlers/overview/#migrate-to-the-experimental-python-handler

**Comment by tomchristie** [comment]
What benefit/changes would upgrading the python handler have for the documentation?

**Comment by madkinsz** [comment]
You can see the list of features for the new handler at https://mkdocstrings.github.io/python/ — it seems like this would only be useful if you want to include a generated API reference in the documentation though.

**Comment by tomchristie** [comment]
Okay, thanks for the suggestion.

If anyone's sufficiently motivated to open a pull request, and can demo which bits of the docs would change as a result then I'd be up for reviewing that.
