### ISSUE TITLE
Bring back TRACE logs

### ISSUE THREAD

**Issue by florimondmanca** [encode/httpcore#58]
I notice the `logger.trace()` calls we had previously in HTTPX are not present in this package anymore.

I suppose this was done out of simplicity, but I think we should bring them back. They were super useful to debug networking issues, connection management issues, etc.

So here's an issue for trackig purposes. :-)

**Comment by tomchristie** [comment]
Yeah that's my fault,

I think it was while I was trying to do a bit of refactoring of the HTTP/2 and pulling everything across to httpcore. Is it clear what environment variable naming we ought to be using given that we've got a proper httpx/httpcore split now?

**Comment by florimondmanca** [comment]
For env vars we could have an HTTPCORE_LOG_LEVEL, and make HTTPX set that when HTTPX_LOG_LEVEL is set too.

**Comment by tomchristie** [comment]
Sounds reasonable yeah
