### ISSUE TITLE
recv on httpcore/backends/sync.py raise BlockingIOError error when tcp keep alive enabled

### ISSUE THREAD

**Issue by CastagnaIT** [encode/httpcore#599]
I'm using httpx with http2 that use this module as dependency (python 3.9.14 embedded on android app)

in the past an httpx dev has suggest me to enable tcp keep alive in this way:
https://github.com/CastagnaIT/plugin.video.netflix/commit/86e15b610f5bd6c30742f59cb876d58d5ea71d1a
(i need it otherwise i receive always connection reset errors)
this has always work good but the httpx version was the 0.18.2 and relative depends like httpcore was 0.13.6

now i am updating httpx to last version 0.23.0, and this require httpcore 0.15.0
i have reapplied the tcp keep alive in httpcore as follows:
https://github.com/CastagnaIT/plugin.video.netflix/pull/1485/commits/30f6f64b4cb27f707419662dbd88a6cc03c41da5

but the problem is that httpcore now always raise BlockingIOError error
where in the old version 0.13.6 not happens

full stack trace here: https://paste.kodi.tv/urozubekiv
[stacktrace.txt](https://github.com/encode/httpcore/files/9973250/stacktrace.txt)

i have no idea how to fix this
seems that recent 0.14 rework may caused a kind of regression

**Comment by tomchristie** [comment]
Are you able to provide a URL to test this against, and a working example?

**Comment by CastagnaIT** [comment]
unfurnately not, this because you need a n€tflix account, building an example that works without the Kodi ecosystem its too huge job that takes too many hours due to complexity of n€tflix website

but if you are able to get a n€tflix account i can provide instructions on how test it with Kodi software
