### ISSUE TITLE
Proxy modes

### ISSUE THREAD

**Issue by yeraydiazdiaz** [encode/httpcore#65]
Two issues stemming from discussions in https://github.com/encode/httpcore/pull/57:

1. Whether the logic behind using tunnelling or forwarding depending on the scheme of the request, i.e. forward if HTTP, tunnel if HTTPS, belongs in HTTPCore.
~2. A discrepancy in how we deal with proxy headers between the two modes. Currently forwading  extends the headers in the request with the `proxy_headers` argument, but tunneling _only_ includes the `proxy_headers`. This forces the user into carefully constructing the proxy headers argument depending on the proxy mode which is annoying and also may result in unexpected errors when using the default proxy mode and requesting a mix of HTTP and HTTPS URLs.~

**Comment by tomchristie** [comment]
So, I kinda agree that it'd be nice for the HTTPCore API to *not* support a "default" mode that switches depending on http/https requests.

However that *does* impact the `httpx` implementation. In particular, for the default case we'd need to mount *two* transport instances, eg...

```python
{
    "http": httpcore.AsyncProxyTransport(mode="FORWARD"),
    "https": httpcore.AsyncProxyTransport(mode="TUNNEL"),
}
```

(Forgive any errors there, I'm just sketching it out.)

I'd suggest that a good *tack* onto getting there would be to *start* with a PR to `httpx` that no longer uses the DEFAULT mode anywhere. That'd help us thrash out & review any implementation changes required in `httpx`, without *actually* changing any API in `httpcore` or `httpx`.

**Comment by yeraydiazdiaz** [comment]
Thanks, I opened https://github.com/encode/httpx/pull/927 to that effect.

Also moving the discussion about headers to another issue.

**Comment by tomchristie** [comment]
Closing in line with https://github.com/encode/httpx/pull/927
