### ISSUE TITLE
AsyncIOStream class initializer raises AttributeError: module 'anyio' has no attribute 'abc'

### ISSUE THREAD

**Issue by elliottmoos** [encode/httpcore#660]
Hi folks.

I'm experiencing an issue with the downstream `httpx` library's `AsyncClient`.

```python
resp = await self.session.get()
httpcore/backends/asyncio.py", line 20, in AsyncIOStream
    def __init__(self, stream: anyio.abc.ByteStream) -> None:
AttributeError: module 'anyio' has no attribute 'abc'
```

It's worth mentioning that the virtual environment this is running in seems to have the most up-to-date version of `httpx`, `httpcore`, and `anyio` installed. In an iPython session I can import `ByteStream` as well. But at runtime, I'm met with that stack trace. 

It seems like `anyio` is being imported or referenced in a way that might be inconsistent with its documentation. 

For the `anyio` [3.0.0 major release](https://anyio.readthedocs.io/en/stable/versionhistory.html), the changelog mentions a breaking change where every submodule of the `anyio.abc` submodule was made private. 

This seems like it could be some very confusing runtime problem, or something simple that I've just missed in my usage of `httpx`.

If anyone has any advice on how to debug this, that would be greatly appreciated!

Thanks

**Comment by tomchristie** [comment]
I'm not able to replicate this...

```shell
$ venv/bin/pip freeze | grep anyio
anyio==3.6.2
$ venv/bin/python
Python 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import anyio
>>> anyio.abc.ByteStream
<class 'anyio.abc.ByteStream'>
>>> exit()
```

**Comment by elliottmoos** [comment]
> I'm not able to replicate this...
> 
> ```shell
> $ venv/bin/pip freeze | grep anyio
> anyio==3.6.2
> $ venv/bin/python
> Python 3.10.9 (v3.10.9:1dd9be6584, Dec  6 2022, 14:37:36) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import anyio
> >>> anyio.abc.ByteStream
> <class 'anyio.abc.ByteStream'>
> >>> exit()
> ```
> 
> Are you able to check what version of `anyio` you've got installed, and if you're able to run the above okay?

Thanks for taking a look!

```python
anyio==3.6.2
Python 3.10.6 (main, Jan 30 2023, 12:43:21) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import anyio
>>> anyio.abc.ByteStream
<class 'anyio.abc.ByteStream'>
>>> exit()
```

The issue doesn't seem to happen when running it in a REPL like this, but at runtime, inside a container.
