### ISSUE TITLE
how to set cookie in httpcore 

### ISSUE THREAD

**Issue by houoop** [encode/httpcore#76]
```
import asyncio
import httpcore

async def main():
    headers = proxy_headers = [(b"host", b"google.org")]
    async with httpcore.AsyncHTTPProxy(
            (b'http',b'127.0.0.1',12590),
            proxy_headers=proxy_headers,
            http2=True,
    ) as http:
        http_version, status_code, reason_phrase, headers, stream = await http.request(
            method=b'GET',
            url=(b'https', b'www.google.com', 443, b'/'), headers=headers,
        )
        try:
            body = []
            async for chunk in stream:
                body.append(chunk)
            print(b"".join(body))
        except Exception as e:
            print(e)
        finally:
            await stream.aclose()

asyncio.run(main())
```
This is my sample code , I want to set a cookie (like a dict, {"xxxx": 'aaaa'}) for this request. But I don't know where to set.

**Comment by tomchristie** [comment]
Heya - you'd probably do better to take usage questions to https://gitter.im/encode/community

Also, from the docs... 

> "You probably don't want to be using HTTP Core directly. It might make sense if you're writing something like a proxy service in Python, and you just want something at the lowest possible level, but more typically you'll want to use a higher level client library, such as httpx."

If you're adding in cookies, perhaps look at using `httpx` instead, since it provides that level of interface for you.
