### ISSUE TITLE
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

### ISSUE THREAD

**Issue by 0xmada** [encode/httpcore#804]
AttributeError: module 'httpcore' has no attribute 'NetworkBackend'

**Comment by zanieb** [comment]
Hi! When you open issues you should provide a lot more information like the context in which the error occurred, a minimal code snippet to reproduce it, and the full error traceback. See https://github.com/sqlalchemy/sqlalchemy/issues/7878 for an example.

In this project, we also request that you [open a discussion](https://github.com/encode/httpcore/discussions) before an issue. Feel free to open a discussion if you include more details.
