### ISSUE TITLE
Breaking changes release in version 0.3.1

### ISSUE THREAD

**Issue by harveyxia** [encode/httpcore#84]
The [`requests-async`](https://github.com/encode/requests-async) library depends on httpcore 0.3.*, which is now failing for me when running httpcore 0.3.1—specifically [this line](https://github.com/encode/requests-async/blob/23c21e05721d1bc6fbd270727782a495ae4ca228/requests_async/adapters.py#L55) with  `request() got an unexpected keyword argument 'ssl'`

@tomchristie I'm guessing that version 0.4.0 of httpcore was accidentally released under version tag 0.3.1?

**Comment by tomchristie** [comment]
Try uninstalling and re-installing httpcore. The 0.3.1 release has been deleted from PyPI, so you should end up with 0.3.0.
