### ISSUE TITLE
Don't exceed `MAX_CONCURRENT_STREAMS` when sending HTTP/2 requests

### ISSUE THREAD

**Issue by sethmlarson** [encode/httpcore#85]
Bug described in encode/httpx#281 where HTTPX doesn't support waiting for other streams to close before creating a new stream on an HTTP/2 connection.

**Comment by yeraydiazdiaz** [comment]
Yep, this issue is still present.

**Comment by tomchristie** [comment]
Okay, so there's two related bit here...

* Honoring MAX_CONCURRENT_STREAMS.
* Reconnecting on `NO_ERROR` eg. https://github.com/encode/httpcore/issues/45 and also comment in https://github.com/encode/httpcore/issues/87#issuecomment-603769264 (Eg. Apparently nginx *doesn't* issue a `max_stream_id`, but will close the connection after 1000 streams, so we need to gracefully re-issue requests for that case.)

**Comment by tomchristie** [comment]
We should raise `NewConnectionRequired()` in either of those cases.

Are we already dealing with the MAX_CONCURRENT_STREAMS case, here?... https://github.com/encode/httpcore/blob/master/httpcore/_async/http2.py#L94-L98

**Comment by tomchristie** [comment]
Blergh, sorry - I'm mixing up max concurrent streams vs. max stream id.

**Comment by tomchristie** [comment]
I suppose we want to wrap this block up in a semaphore...

https://github.com/encode/httpcore/blob/master/httpcore/_async/http2.py#L102-L105

**Comment by tomchristie** [comment]
So, looks to me like https://github.com/encode/httpcore/pull/38/files has it about right, but really we should wrap the semaphore around the post-init part of the request method.
