### ISSUE TITLE
Use `aclose()` for async close methods.

### ISSUE THREAD

**Issue by tomchristie** [encode/httpcore#9]

**Comment by victoraugustolls** [comment]
Is this to just rename existing `async def close()` methods to `async def aclose()`? If it is, I can open a quick PR for this!

**Comment by tomchristie** [comment]
Kinda yes. You'll also need to add `aclose`->`close` to the `scripts/unasync` script,  which is used to autogenerate the sync case from the async case. (And also used at CI to check that the two implementations matche up correctly.)

**Comment by tomchristie** [comment]
Closed via  #35
