### ISSUE TITLE
Use __future__.annotations

### ISSUE THREAD

**Issue by zrquan** [encode/httpcore#962]
### Discussed in https://github.com/encode/httpcore/discussions/954

<div type='discussions-op-text'>

<sup>Originally posted by **zrquan** September 26, 2024</sup>
Use the new typing style, just like [in httpx](https://github.com/encode/httpx/pull/3068/files).</div>

The new type hints are more concise and easier to read.

Before:
```python
def request(
    method: Union[bytes, str],
    url: Union[URL, bytes, str],
    *,
    headers: HeaderTypes = None,
    content: Union[bytes, Iterator[bytes], None] = None,
    extensions: Optional[Extensions] = None,
) -> Response:
    ...
```

After:
```python
def request(
    method: bytes | str,
    url: URL | bytes | str,
    *,
    headers: HeaderTypes = None,
    content: bytes | Iterator[bytes] | None = None,
    extensions: Extensions | None = None,
) -> Response:
    ...
```

**Comment by tomchristie** [comment]
Sure thing yep. Would you like to try dealing with a pull request for this?

**Comment by zrquan** [comment]
> Would you like to try dealing with a pull request for this?

Sure, I'd be happy to handle it.
